import { readFileSync, writeFileSync } from "node:fs"

const GET_PROFILE_URL = "https://api.github.com/users/bfpimentel"

type ProfileResponse = {
  name: string
  avatar_url: string
  bio: string
  company: string
}

interface RepositoryResponse {
  author: string
  name: string
  description: string
  language: string
  languageColor?: string
  stars?: number
  forks?: number
}

interface ProfileModel {
  name: string
  photoUrl: string
  bio: string
  projects: { name: string; description: string; link: string }[]
}

async function getGithubProfile(): Promise<ProfileModel> {
  return fetch(GET_PROFILE_URL).then(async (profileResponse) => {
    const parsedProfile = (await profileResponse.json()) as ProfileResponse
    const pinnedRepositories = await fetch("https://pinned.berrysauce.dev/get/bfpimentel")
    const parsedPinnedRepositories = (await pinnedRepositories.json()) as RepositoryResponse[]

    return {
      name: parsedProfile.name,
      photoUrl: parsedProfile.avatar_url,
      bio: parsedProfile.bio,
      projects: parsedPinnedRepositories.map((repo) => ({
        name: repo.name,
        description: repo.description,
        link: `https://github.com/bfpimentel/${repo.name}`,
      })),
    }
  })
}

async function generate_profile() {
  const profile = await getGithubProfile()
  const filePath = "src/pages/Home.tsx"
  const content = readFileSync(filePath, "utf-8")

  const tag = "/* AUTO-GENERATED BY generate_profile.ts */"
  const startIndex = content.indexOf(tag)
  const endIndex = content.lastIndexOf(tag)

  if (startIndex === -1 || endIndex === -1 || startIndex === endIndex) {
    console.error("Tags not found in Home.tsx")
    process.exit(1)
  }

  const profileString = `const profile = ${JSON.stringify(profile, null, 2)}`
  const newContent =
    content.substring(0, startIndex + tag.length) +
    "\n" +
    profileString +
    "\n" +
    content.substring(endIndex)

  writeFileSync(filePath, newContent)

  console.log("Profile generated successfully!")
}

generate_profile()
