import { Link } from "react-router-dom";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Logo from "@/components/Logo";
import Projects from "@/components/Projects";
import SEO from "@/components/SEO";

/* AUTO-GENERATED BY generate_profile.ts */
const profile = {
  name: "Bruno Pimentel",
  photoUrl: "https://avatars.githubusercontent.com/u/40500313?v=4",
  bio: "Senior Software Engineer. Generalist. I adapt to anything.",
  projects: [
    {
      name: "dotfiles",
      description:
        "Personal dotfiles with automated setup using Nix and Home Manager",
      link: "https://github.com/bfpimentel/dotfiles",
    },
    {
      name: "bitwarden-mxroute",
      description:
        "Fake Addy.io Server for creating aliases inside Bitwarden using MXRoute API",
      link: "https://github.com/bfpimentel/bitwarden-mxroute",
    },
    {
      name: "ad-aeternum",
      description:
        "Interactive Rosary app for iOS and Android using React Native and Expo",
      link: "https://github.com/bfpimentel/ad-aeternum",
    },
    {
      name: "drip",
      description:
        "Stupid simple file upload server with real-time updates and auto-expiration",
      link: "https://github.com/bfpimentel/drip",
    },
    {
      name: "shady",
      description: "Auto docker containers dashboard and static file server",
      link: "https://github.com/bfpimentel/shady",
    },
    {
      name: "satellite",
      description:
        "White-noise playback app made with Flutter and controlled by a Flask server",
      link: "https://github.com/bfpimentel/satellite",
    },
  ],
};
/* AUTO-GENERATED BY generate_profile.ts */

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center bg-white font-mono text-zinc-900 selection:bg-zinc-900 selection:text-white dark:bg-zinc-950 dark:text-zinc-100 dark:selection:bg-zinc-100 dark:selection:text-zinc-900">
      <SEO title={profile.name} description={profile.bio} />
      <Logo />
      <main className="flex grow w-full max-w-4xl flex-col items-center p-6">
        <Header
          name={profile.name}
          photoUrl={profile.photoUrl}
          bio={profile.bio}
        />
        <a
          className="text-lg mt-8 font-bold uppercase tracking-widest text-zinc-500 hover:text-zinc-900 hover:underline dark:text-zinc-400 dark:hover:text-white"
          href="/resume.pdf"
        >
          Resume →
        </a>
        <Link
          to="/blog"
          className="text-lg mt-4 font-bold uppercase tracking-widest text-zinc-500 hover:text-zinc-900 hover:underline dark:text-zinc-400 dark:hover:text-white"
        >
          Blog →
        </Link>
        <div className="my-8 w-full border-b border-zinc-200 dark:border-zinc-800 sm:my-8" />
        <Projects projects={profile.projects} />
      </main>
      <Footer />
    </div>
  );
}
